version: 2
mergeable:
  - when: pull_request.opened
    name: "Greet a contributor"
    validate: []
    pass:
      - do: assign
        assignees: [ '@author' ] # only array accepted, use @author for PR/Issue author
      - do: request_review
        reviewers: ['SeonHyungJo', 'CallbusLab']
      - do: labels
        # if label doesn't exist, it'll be created
        labels: [ 'status: pending' ] # All labels beginning with 'feature-' will be removed
        mode: 'add'
  - when: pull_request.edited, pull_request.opened
    name: "Set Type Label"
    validate: 
      - do: title
        must_include:
          regex: 'feat'
          message: 'Custom message...'
    pass:
      - do: labels
        labels: [ 'type:*' ]
        mode: 'delete'
      - do: labels
        labels: [ 'type: feat' ]
        mode: 'add'
  - when: pull_request.edited, pull_request.opened
    name: "Set Type Label"
    validate: 
      - do: title
        must_include:
          regex: 'build'
          message: 'Custom message...'
    pass:
      - do: labels
        labels: [ 'type:*' ]
        mode: 'delete'
      - do: labels
        labels: [ 'type: build' ]
        mode: 'add'
  - when: pull_request.edited, pull_request.opened
    name: "Set Type Label"
    validate: 
      - do: title
        must_include:
          regex: 'chore'
          message: 'Custom message...'
    pass:
      - do: labels
        labels: [ 'type:*' ]
        mode: 'delete'
      - do: labels
        labels: [ 'type: chore' ]
        mode: 'add'
  - when: pull_request.edited, pull_request.opened
    name: "Set Type Label"
    validate: 
      - do: title
        must_include:
          regex: 'style'
          message: 'Custom message...'
    pass:
      - do: labels
        labels: [ 'type:*' ]
        mode: 'delete'
      - do: labels
        labels: [ 'type: style' ]
        mode: 'add'
  - when: pull_request.edited, pull_request.opened
    name: "Set Type Label"
    validate: 
      - do: title
        must_include:
          regex: 'ci'
          message: 'Custom message...'
    pass:
      - do: labels
        labels: [ 'type:*' ]
        mode: 'delete'
      - do: labels
        labels: [ 'type: ci' ]
        mode: 'add'
  - when: pull_request.edited, pull_request.opened
    name: "Set Type Label"
    validate: 
      - do: title
        must_include:
          regex: 'docs'
          message: 'Custom message...'
    pass:
      - do: labels
        labels: [ 'type:*' ]
        mode: 'delete'
      - do: labels
        labels: [ 'type: docs' ]
        mode: 'add'
  - when: pull_request.edited, pull_request.opened
    name: "Set Type Label"
    validate:
      - do: title
        must_include:
          regex: 'fix'
          message: 'Custom message...'
    pass:
      - do: labels
        labels: [ 'type:*' ]
        mode: 'delete'
      - do: labels
        labels: [ 'type: fix' ]
        mode: 'add'
  - when: pull_request.edited, pull_request.opened
    name: "Set Type Label"
    validate: 
      - do: title
        must_include:
          regex: 'perf'
          message: 'Custom message...'
    pass:
      - do: labels
        labels: [ 'type:*' ]
        mode: 'delete'
      - do: labels
        labels: [ 'type: perf' ]
        mode: 'add'
  - when: pull_request.edited, pull_request.opened
    name: "Set Type Label"
    validate: 
      - do: title
        must_include:
          regex: 'refactor'
          message: 'Custom message...'
    pass:
      - do: labels
        labels: [ 'type:*' ]
        mode: 'delete'
      - do: labels
        labels: [ 'type: refactor' ]
        mode: 'add'
        
  - when: pull_request_review
    name: "Review"
    pass:
      - do: comment
        payload:
          body: >
            Review