version: 2
mergeable:
  - when: pull_request.opened
    name: "Greet a contributor"
    validate: []
    pass:
      - do: assign
        assignees: [ '@author' ] # only array accepted, use @author for PR/Issue author
      - do: request_review
        reviewers: ['SeonHyungJo', 'CallbusLab']
      - do: labels
        # if label doesn't exist, it'll be created
        labels: [ 'type-a', 'bug' ] # All labels beginning with 'feature-' will be removed
        mode: 'add'
  - when: pull_request.*
    name: Check Approval
    validate: 
      - do: approvals
        min:
          count: 1 # Number of minimum reviewers. In this case 2.
          message: 'Custom message...'
        limit:
          users: ['SeonHyungJo', 'CallbusLab'] # when the option is present, approvals from users in this list will count
        block:
          changes_requested: true # If true, block all approvals when one of the reviewers gave 'changes_requested' review
          message: 'changes_requested'
    pass: 
      - do: merge
        merge_method: 'squash'