version: 2
mergeable:
  - when: pull_request.opened
    validate:
      - do: assignee
        min:
          count: 1 # min number of assignees
          message: '' # this is optional
      - do: assign
        assignees: [ '@author' ] # only array accepted, use @author for PR/Issue author
      - do: request_review
        reviewers: ['SeonHyungJo']
  - when: pull_request.*
    validate:
      - do: description
        no_empty:
          enabled: true
          message: Description을 빈칸으로 할 수 없습니다.