version: 2
mergeable:
  - when: pull_request.opened
    name: "Greet a contributor"
    validate: []
    pass:
      - do: assign
        assignees: [ '@author' ] # only array accepted, use @author for PR/Issue author
      - do: request_review
        reviewers: ['SeonHyungJo']
      - do: labels
        # if label doesn't exist, it'll be created
        labels: [ 'type-a', 'bug' ] # All labels beginning with 'feature-' will be removed
        mode: 'add'
  - when: pull_request.*
    validate:
      - do: description
        no_empty:
          enabled: true
          message: Description을 빈칸으로 할 수 없습니다.