version: 2
mergeable:
  - when: pull_request.opened
    name: "Greet a contributor"
    validate: []
    pass:
      - do: assign
        assignees: [ '@author' ] # only array accepted, use @author for PR/Issue author
      - do: request_review
        reviewers: ['SeonHyungJo', 'CallbusLab']
      - do: labels
        # if label doesn't exist, it'll be created
        labels: [ 'type-a', 'bug' ] # All labels beginning with 'feature-' will be removed
        mode: 'add'
  - when: pull_request.*
    name: Check Approval
    validate:
      - do: approvals
        required:
          requested_reviewers: true # Optional boolean. When true, all the requested reviewer's approval is required
          message: '승인해주세요'
        # min:
        #   count: 1 # Number of minimum reviewers. In this case 2.
        #   message: '최소 1명의 승인이 필요합니다.'
    pass: 
      - do: merge
        merge_method: 'squash'